### ISSUE TITLE
Firmware 4.23.15505 main navigation changes

### ISSUE THREAD

**Issue by pgaskin** [pgaskin/NickelMenu#78]
MR:post-4021495
MR:thread-332254

**Comment by pgaskin** [comment]
NickelMenu is still safe to use, but the main menu items won't appear anymore. In addition, at least `nickel_open` and `nickel_misc:home` will need to be tested again to ensure they still work.

To put back support for the main menu, I can either turn the new clock which replaced it into a new menu, or I can add to the "More" tab, or both.

I haven't decided whether I'm going to release this as `v0.4.0` or `v0.3.2`. I'll probably decide based on how likely the necessary changes may inadvertently cause regressions for older firmware versions.

**Comment by pgaskin** [comment]
After a preliminary look at libnickel, I think it's more likely that I'm going to add another button to the bottom nav rather than adding items to the More menu itself. It appears to be safer and easier to hook, plus it'll be easier to use and there's enough empty space for another button (which would even make it look nicer IMO). I haven't looked into the option of replacing the clock yet.

The main disadvantage of both these methods is that I'll actually have to figure out the details of how touch input handling works in nickel.

**Comment by pgaskin** [comment]
The first thing I'm going to look into is showing a custom TouchMenu, as I'll be able to test this on older firmware versions and it'll be easier to debug things later if I figure this out first.

**Comment by pgaskin** [comment]
Qt resources from 15015:

<details><summary><b>qss/StatusBarMenu.qss</b></summary>

```css
TouchMenu {
  padding: 10px;
  border: 3px solid black;
  background-color: white;
}
TouchMenu::separator {
  height: 1px;
  background-color: #666666;
  margin-top: 5px;
  margin-bottom: 5px;
}
TouchMenu {
  border: none;
}
NickelTouchMenu {
  background-color: transparent;
  margin: 14px;
}
MenuTextItem,
MenuImageItem {
  background-color: white;
}
MenuTextItem[qApp_deviceIsTrilogy=true],
MenuImageItem[qApp_deviceIsTrilogy=true] {
  min-width: 200px;
}
MenuTextItem[qApp_deviceIsPhoenix=true],
MenuImageItem[qApp_deviceIsPhoenix=true] {
  min-width: 220px;
}
MenuTextItem[qApp_deviceIsDragon=true],
MenuImageItem[qApp_deviceIsDragon=true] {
  min-width: 300px;
}
MenuTextItem[qApp_deviceIsDaylight=true],
MenuImageItem[qApp_deviceIsDaylight=true] {
  min-width: 390px;
}
MenuTextItem[qApp_deviceIsStorm=true],
MenuImageItem[qApp_deviceIsStorm=true] {
  min-width: 350px;
}
MenuTextItem[qApp_deviceIsTrilogy=true] {
  min-height: 46px;
  max-height: 46px;
}
MenuTextItem[qApp_deviceIsPhoenix=true] {
  min-height: 56px;
  max-height: 56px;
}
MenuTextItem[qApp_deviceIsDragon=true] {
  min-height: 70px;
  max-height: 70px;
}
MenuTextItem[qApp_deviceIsDaylight=true] {
  min-height: 90px;
  max-height: 90px;
}
MenuTextItem[qApp_deviceIsStorm=true] {
  min-height: 80px;
  max-height: 80px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsTrilogy=true] {
  min-height: 57px;
  max-height: 57px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsPhoenix=true] {
  min-height: 70px;
  max-height: 70px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsDragon=true] {
  min-height: 87px;
  max-height: 87px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsDaylight=true] {
  min-height: 112px;
  max-height: 112px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsStorm=true] {
  min-height: 98px;
  max-height: 98px;
}
MenuTextItem #menuTextItemLabel[italics=true] {
  font-family: Georgia;
  font-style: italic;
}
MenuTextItem #menuTextItemLabel {
  qproperty-leading: 0;
  background-color: white;
  color: black;
}
MenuTextItem #menuTextItemLabel[localeName=\"ja\"] {
  font-family: Sans-SerifJP, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[localeName=\"zh\"] {
  font-family: Sans-SerifZH-Simplified, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[localeName=\"zh-HK\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[localeName=\"zh-TW\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsTrilogy=true] {
  font-size: 19px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsPhoenix=true] {
  font-size: 23px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDragon=true] {
  font-size: 29px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsAlyssum=true] {
  font-size: 32px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsNova=true] {
  font-size: 32px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsStorm=true] {
  font-size: 34px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDaylight=true] {
  font-size: 37px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsTrilogy=true] {
  padding-top: 2px;
  padding-bottom: 2px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsPhoenix=true] {
  padding-top: 3px;
  padding-bottom: 3px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDragon=true] {
  padding-top: 4px;
  padding-bottom: 4px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDaylight=true] {
  padding-top: 5px;
  padding-bottom: 5px;
}
MenuTextItem #menuTextItemLabel:disabled {
  color: #999999;
}
#sectionLabel[localeName=\"ja\"],
#sectionTitle[localeName=\"ja\"] {
  font-family: Sans-SerifJP, sans-serif;
  font-style: normal;
}
#sectionLabel[localeName=\"zh\"],
#sectionTitle[localeName=\"zh\"] {
  font-family: Sans-SerifZH-Simplified, sans-serif;
  font-style: normal;
}
#sectionLabel[localeName=\"zh-HK\"],
#sectionTitle[localeName=\"zh-HK\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
#sectionLabel[localeName=\"zh-TW\"],
#sectionTitle[localeName=\"zh-TW\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
#sectionLabel[qApp_deviceIsTrilogy=true],
#sectionTitle[qApp_deviceIsTrilogy=true] {
  min-height: 46px;
  max-height: 46px;
}
#sectionLabel[qApp_deviceIsPhoenix=true],
#sectionTitle[qApp_deviceIsPhoenix=true] {
  min-height: 56px;
  max-height: 56px;
}
#sectionLabel[qApp_deviceIsDragon=true],
#sectionTitle[qApp_deviceIsDragon=true] {
  min-height: 70px;
  max-height: 70px;
}
#sectionLabel[qApp_deviceIsDaylight=true],
#sectionTitle[qApp_deviceIsDaylight=true] {
  min-height: 90px;
  max-height: 90px;
}
#sectionLabel[qApp_deviceIsStorm=true],
#sectionTitle[qApp_deviceIsStorm=true] {
  min-height: 80px;
  max-height: 80px;
}
#sectionLabel[qApp_deviceIsTrilogy=true],
#sectionTitle[qApp_deviceIsTrilogy=true] {
  padding-left: 12px;
}
#sectionLabel[qApp_deviceIsPhoenix=true],
#sectionTitle[qApp_deviceIsPhoenix=true] {
  padding-left: 16px;
}
#sectionLabel[qApp_deviceIsDragon=true],
#sectionTitle[qApp_deviceIsDragon=true] {
  padding-left: 22px;
}
#sectionLabel[qApp_deviceIsDaylight=true],
#sectionTitle[qApp_deviceIsDaylight=true] {
  padding-left: 28px;
}
#sectionLabel[qApp_deviceIsStorm=true],
#sectionTitle[qApp_deviceIsStorm=true] {
  padding-left: 25px;
}
#sectionLabel[qApp_deviceIsTrilogy=true],
#sectionTitle[qApp_deviceIsTrilogy=true] {
  font-size: 17px;
}
#sectionLabel[qApp_deviceIsPhoenix=true],
#sectionTitle[qApp_deviceIsPhoenix=true] {
  font-size: 22px;
}
#sectionLabel[qApp_deviceIsDragon=true],
#sectionTitle[qApp_deviceIsDragon=true] {
  font-size: 26px;
}
#sectionLabel[qApp_deviceIsAlyssum=true],
#sectionTitle[qApp_deviceIsAlyssum=true] {
  font-size: 30px;
}
#sectionLabel[qApp_deviceIsNova=true],
#sectionTitle[qApp_deviceIsNova=true] {
  font-size: 30px;
}
#sectionLabel[qApp_deviceIsStorm=true],
#sectionTitle[qApp_deviceIsStorm=true] {
  font-size: 30px;
}
#sectionLabel[qApp_deviceIsDaylight=true],
#sectionTitle[qApp_deviceIsDaylight=true] {
  font-size: 34px;
}
#acceptButton {
  qproperty-primaryButton: true;
}
#rejectButton {
  qproperty-primaryButton: false;
}
StatusBarMenu[qApp_deviceIsTrilogy=true] {
  margin: 15px;
}
StatusBarMenu[qApp_deviceIsPhoenix=true] {
  margin: 20px;
}
StatusBarMenu[qApp_deviceIsDragon=true] {
  margin: 30px;
}
StatusBarMenu[qApp_deviceIsDaylight=true] {
  margin: 39px;
}
StatusBarMenu[qApp_deviceIsStorm=true] {
  margin: 35px;
}
MenuTextItem #leftSpacer[qApp_deviceIsTrilogy=true],
MenuTextItem #rightSpacer[qApp_deviceIsTrilogy=true] {
  max-width: 12px;
  min-width: 12px;
}
MenuTextItem #leftSpacer[qApp_deviceIsPhoenix=true],
MenuTextItem #rightSpacer[qApp_deviceIsPhoenix=true] {
  max-width: 15px;
  min-width: 15px;
}
MenuTextItem #leftSpacer[qApp_deviceIsDragon=true],
MenuTextItem #rightSpacer[qApp_deviceIsDragon=true] {
  max-width: 20px;
  min-width: 20px;
}
MenuTextItem #leftSpacer[qApp_deviceIsDaylight=true],
MenuTextItem #rightSpacer[qApp_deviceIsDaylight=true] {
  max-width: 26px;
  min-width: 26px;
}
MenuTextItem #leftSpacer[qApp_deviceIsStorm=true],
MenuTextItem #rightSpacer[qApp_deviceIsStorm=true] {
  max-width: 23px;
  min-width: 23px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsTrilogy=true] {
  font-size: 19px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsPhoenix=true] {
  font-size: 23px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDragon=true] {
  font-size: 32px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsStorm=true] {
  font-size: 37px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDaylight=true] {
  font-size: 42px;
}
```

</details>

<details><summary><b>qss/NickelTouchMenu.qss</b></summary>

```css
TouchMenu {
  border: none;
}
NickelTouchMenu {
  background-color: transparent;
  margin: 14px;
}
MenuTextItem,
MenuImageItem {
  background-color: white;
}
MenuTextItem[qApp_deviceIsTrilogy=true],
MenuImageItem[qApp_deviceIsTrilogy=true] {
  min-width: 200px;
}
MenuTextItem[qApp_deviceIsPhoenix=true],
MenuImageItem[qApp_deviceIsPhoenix=true] {
  min-width: 220px;
}
MenuTextItem[qApp_deviceIsDragon=true],
MenuImageItem[qApp_deviceIsDragon=true] {
  min-width: 300px;
}
MenuTextItem[qApp_deviceIsDaylight=true],
MenuImageItem[qApp_deviceIsDaylight=true] {
  min-width: 390px;
}
MenuTextItem[qApp_deviceIsStorm=true],
MenuImageItem[qApp_deviceIsStorm=true] {
  min-width: 350px;
}
MenuTextItem[qApp_deviceIsTrilogy=true] {
  min-height: 46px;
  max-height: 46px;
}
MenuTextItem[qApp_deviceIsPhoenix=true] {
  min-height: 56px;
  max-height: 56px;
}
MenuTextItem[qApp_deviceIsDragon=true] {
  min-height: 70px;
  max-height: 70px;
}
MenuTextItem[qApp_deviceIsDaylight=true] {
  min-height: 90px;
  max-height: 90px;
}
MenuTextItem[qApp_deviceIsStorm=true] {
  min-height: 80px;
  max-height: 80px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsTrilogy=true] {
  min-height: 57px;
  max-height: 57px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsPhoenix=true] {
  min-height: 70px;
  max-height: 70px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsDragon=true] {
  min-height: 87px;
  max-height: 87px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsDaylight=true] {
  min-height: 112px;
  max-height: 112px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsStorm=true] {
  min-height: 98px;
  max-height: 98px;
}
MenuTextItem #menuTextItemLabel[italics=true] {
  font-family: Georgia;
  font-style: italic;
}
MenuTextItem #menuTextItemLabel {
  qproperty-leading: 0;
  background-color: white;
  color: black;
}
MenuTextItem #menuTextItemLabel[localeName=\"ja\"] {
  font-family: Sans-SerifJP, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[localeName=\"zh\"] {
  font-family: Sans-SerifZH-Simplified, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[localeName=\"zh-HK\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[localeName=\"zh-TW\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsTrilogy=true] {
  font-size: 19px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsPhoenix=true] {
  font-size: 23px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDragon=true] {
  font-size: 29px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsAlyssum=true] {
  font-size: 32px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsNova=true] {
  font-size: 32px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsStorm=true] {
  font-size: 34px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDaylight=true] {
  font-size: 37px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsTrilogy=true] {
  padding-top: 2px;
  padding-bottom: 2px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsPhoenix=true] {
  padding-top: 3px;
  padding-bottom: 3px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDragon=true] {
  padding-top: 4px;
  padding-bottom: 4px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDaylight=true] {
  padding-top: 5px;
  padding-bottom: 5px;
}
MenuTextItem #menuTextItemLabel:disabled {
  color: #999999;
}
#sectionLabel[localeName=\"ja\"],
#sectionTitle[localeName=\"ja\"] {
  font-family: Sans-SerifJP, sans-serif;
  font-style: normal;
}
#sectionLabel[localeName=\"zh\"],
#sectionTitle[localeName=\"zh\"] {
  font-family: Sans-SerifZH-Simplified, sans-serif;
  font-style: normal;
}
#sectionLabel[localeName=\"zh-HK\"],
#sectionTitle[localeName=\"zh-HK\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
#sectionLabel[localeName=\"zh-TW\"],
#sectionTitle[localeName=\"zh-TW\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
#sectionLabel[qApp_deviceIsTrilogy=true],
#sectionTitle[qApp_deviceIsTrilogy=true] {
  min-height: 46px;
  max-height: 46px;
}
#sectionLabel[qApp_deviceIsPhoenix=true],
#sectionTitle[qApp_deviceIsPhoenix=true] {
  min-height: 56px;
  max-height: 56px;
}
#sectionLabel[qApp_deviceIsDragon=true],
#sectionTitle[qApp_deviceIsDragon=true] {
  min-height: 70px;
  max-height: 70px;
}
#sectionLabel[qApp_deviceIsDaylight=true],
#sectionTitle[qApp_deviceIsDaylight=true] {
  min-height: 90px;
  max-height: 90px;
}
#sectionLabel[qApp_deviceIsStorm=true],
#sectionTitle[qApp_deviceIsStorm=true] {
  min-height: 80px;
  max-height: 80px;
}
#sectionLabel[qApp_deviceIsTrilogy=true],
#sectionTitle[qApp_deviceIsTrilogy=true] {
  padding-left: 12px;
}
#sectionLabel[qApp_deviceIsPhoenix=true],
#sectionTitle[qApp_deviceIsPhoenix=true] {
  padding-left: 16px;
}
#sectionLabel[qApp_deviceIsDragon=true],
#sectionTitle[qApp_deviceIsDragon=true] {
  padding-left: 22px;
}
#sectionLabel[qApp_deviceIsDaylight=true],
#sectionTitle[qApp_deviceIsDaylight=true] {
  padding-left: 28px;
}
#sectionLabel[qApp_deviceIsStorm=true],
#sectionTitle[qApp_deviceIsStorm=true] {
  padding-left: 25px;
}
#sectionLabel[qApp_deviceIsTrilogy=true],
#sectionTitle[qApp_deviceIsTrilogy=true] {
  font-size: 17px;
}
#sectionLabel[qApp_deviceIsPhoenix=true],
#sectionTitle[qApp_deviceIsPhoenix=true] {
  font-size: 22px;
}
#sectionLabel[qApp_deviceIsDragon=true],
#sectionTitle[qApp_deviceIsDragon=true] {
  font-size: 26px;
}
#sectionLabel[qApp_deviceIsAlyssum=true],
#sectionTitle[qApp_deviceIsAlyssum=true] {
  font-size: 30px;
}
#sectionLabel[qApp_deviceIsNova=true],
#sectionTitle[qApp_deviceIsNova=true] {
  font-size: 30px;
}
#sectionLabel[qApp_deviceIsStorm=true],
#sectionTitle[qApp_deviceIsStorm=true] {
  font-size: 30px;
}
#sectionLabel[qApp_deviceIsDaylight=true],
#sectionTitle[qApp_deviceIsDaylight=true] {
  font-size: 34px;
}
#acceptButton {
  qproperty-primaryButton: true;
}
#rejectButton {
  qproperty-primaryButton: false;
}
```

</details>

<details><summary><b>qss/TouchMenu.qss</b></summary>

```css
TouchMenu {
	padding: 10px;
	border: 3px solid black;
	background-color: white;
}

TouchMenu::separator {
	height: 1px;
	background-color: #666666;
	margin-top: 5px;
	margin-bottom: 5px;
}
```

</details>

<details><summary><b>qss/GoToPageMenuView.qss</b></summary>

```css
TouchMenu {
  padding: 10px;
  border: 3px solid black;
  background-color: white;
}
TouchMenu::separator {
  height: 1px;
  background-color: #666666;
  margin-top: 5px;
  margin-bottom: 5px;
}
TouchMenu {
  border: none;
}
NickelTouchMenu {
  background-color: transparent;
  margin: 14px;
}
MenuTextItem,
MenuImageItem {
  background-color: white;
}
MenuTextItem[qApp_deviceIsTrilogy=true],
MenuImageItem[qApp_deviceIsTrilogy=true] {
  min-width: 200px;
}
MenuTextItem[qApp_deviceIsPhoenix=true],
MenuImageItem[qApp_deviceIsPhoenix=true] {
  min-width: 220px;
}
MenuTextItem[qApp_deviceIsDragon=true],
MenuImageItem[qApp_deviceIsDragon=true] {
  min-width: 300px;
}
MenuTextItem[qApp_deviceIsDaylight=true],
MenuImageItem[qApp_deviceIsDaylight=true] {
  min-width: 390px;
}
MenuTextItem[qApp_deviceIsStorm=true],
MenuImageItem[qApp_deviceIsStorm=true] {
  min-width: 350px;
}
MenuTextItem[qApp_deviceIsTrilogy=true] {
  min-height: 46px;
  max-height: 46px;
}
MenuTextItem[qApp_deviceIsPhoenix=true] {
  min-height: 56px;
  max-height: 56px;
}
MenuTextItem[qApp_deviceIsDragon=true] {
  min-height: 70px;
  max-height: 70px;
}
MenuTextItem[qApp_deviceIsDaylight=true] {
  min-height: 90px;
  max-height: 90px;
}
MenuTextItem[qApp_deviceIsStorm=true] {
  min-height: 80px;
  max-height: 80px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsTrilogy=true] {
  min-height: 57px;
  max-height: 57px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsPhoenix=true] {
  min-height: 70px;
  max-height: 70px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsDragon=true] {
  min-height: 87px;
  max-height: 87px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsDaylight=true] {
  min-height: 112px;
  max-height: 112px;
}
MenuTextItem[qApp_isFontScaleLarge=true][qApp_deviceIsStorm=true] {
  min-height: 98px;
  max-height: 98px;
}
MenuTextItem #menuTextItemLabel[italics=true] {
  font-family: Georgia;
  font-style: italic;
}
MenuTextItem #menuTextItemLabel {
  qproperty-leading: 0;
  background-color: white;
  color: black;
}
MenuTextItem #menuTextItemLabel[localeName=\"ja\"] {
  font-family: Sans-SerifJP, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[localeName=\"zh\"] {
  font-family: Sans-SerifZH-Simplified, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[localeName=\"zh-HK\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[localeName=\"zh-TW\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsTrilogy=true] {
  font-size: 19px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsPhoenix=true] {
  font-size: 23px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDragon=true] {
  font-size: 29px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsAlyssum=true] {
  font-size: 32px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsNova=true] {
  font-size: 32px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsStorm=true] {
  font-size: 34px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDaylight=true] {
  font-size: 37px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsTrilogy=true] {
  padding-top: 2px;
  padding-bottom: 2px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsPhoenix=true] {
  padding-top: 3px;
  padding-bottom: 3px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDragon=true] {
  padding-top: 4px;
  padding-bottom: 4px;
}
MenuTextItem #menuTextItemLabel[qApp_deviceIsDaylight=true] {
  padding-top: 5px;
  padding-bottom: 5px;
}
MenuTextItem #menuTextItemLabel:disabled {
  color: #999999;
}
#sectionLabel[localeName=\"ja\"],
#sectionTitle[localeName=\"ja\"] {
  font-family: Sans-SerifJP, sans-serif;
  font-style: normal;
}
#sectionLabel[localeName=\"zh\"],
#sectionTitle[localeName=\"zh\"] {
  font-family: Sans-SerifZH-Simplified, sans-serif;
  font-style: normal;
}
#sectionLabel[localeName=\"zh-HK\"],
#sectionTitle[localeName=\"zh-HK\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
#sectionLabel[localeName=\"zh-TW\"],
#sectionTitle[localeName=\"zh-TW\"] {
  font-family: Sans-SerifZH-Traditional, sans-serif;
  font-style: normal;
}
#sectionLabel[qApp_deviceIsTrilogy=true],
#sectionTitle[qApp_deviceIsTrilogy=true] {
  min-height: 46px;
  max-height: 46px;
}
#sectionLabel[qApp_deviceIsPhoenix=true],
#sectionTitle[qApp_deviceIsPhoenix=true] {
  min-height: 56px;
  max-height: 56px;
}
#sectionLabel[qApp_deviceIsDragon=true],
#sectionTitle[qApp_deviceIsDragon=true] {
  min-height: 70px;
  max-height: 70px;
}
#sectionLabel[qApp_deviceIsDaylight=true],
#sectionTitle[qApp_deviceIsDaylight=true] {
  min-height: 90px;
  max-height: 90px;
}
#sectionLabel[qApp_deviceIsStorm=true],
#sectionTitle[qApp_deviceIsStorm=true] {
  min-height: 80px;
  max-height: 80px;
}
#sectionLabel[qApp_deviceIsTrilogy=true],
#sectionTitle[qApp_deviceIsTrilogy=true] {
  padding-left: 12px;
}
#sectionLabel[qApp_deviceIsPhoenix=true],
#sectionTitle[qApp_deviceIsPhoenix=true] {
  padding-left: 16px;
}
#sectionLabel[qApp_deviceIsDragon=true],
#sectionTitle[qApp_deviceIsDragon=true] {
  padding-left: 22px;
}
#sectionLabel[qApp_deviceIsDaylight=true],
#sectionTitle[qApp_deviceIsDaylight=true] {
  padding-left: 28px;
}
#sectionLabel[qApp_deviceIsStorm=true],
#sectionTitle[qApp_deviceIsStorm=true] {
  padding-left: 25px;
}
#sectionLabel[qApp_deviceIsTrilogy=true],
#sectionTitle[qApp_deviceIsTrilogy=true] {
  font-size: 17px;
}
#sectionLabel[qApp_deviceIsPhoenix=true],
#sectionTitle[qApp_deviceIsPhoenix=true] {
  font-size: 22px;
}
#sectionLabel[qApp_deviceIsDragon=true],
#sectionTitle[qApp_deviceIsDragon=true] {
  font-size: 26px;
}
#sectionLabel[qApp_deviceIsAlyssum=true],
#sectionTitle[qApp_deviceIsAlyssum=true] {
  font-size: 30px;
}
#sectionLabel[qApp_deviceIsNova=true],
#sectionTitle[qApp_deviceIsNova=true] {
  font-size: 30px;
}
#sectionLabel[qApp_deviceIsStorm=true],
#sectionTitle[qApp_deviceIsStorm=true] {
  font-size: 30px;
}
#sectionLabel[qApp_deviceIsDaylight=true],
#sectionTitle[qApp_deviceIsDaylight=true] {
  font-size: 34px;
}
#acceptButton {
  qproperty-primaryButton: true;
}
#rejectButton {
  qproperty-primaryButton: false;
}
#label {
  padding-left: 0px;
}
#label[qApp_deviceIsTrilogy=true] {
  font-size: 17px;
}
#label[qApp_deviceIsPhoenix=true] {
  font-size: 22px;
}
#label[qApp_deviceIsDragon=true] {
  font-size: 26px;
}
#label[qApp_deviceIsAlyssum=true] {
  font-size: 30px;
}
#label[qApp_deviceIsNova=true] {
  font-size: 30px;
}
#label[qApp_deviceIsStorm=true] {
  font-size: 30px;
}
#label[qApp_deviceIsDaylight=true] {
  font-size: 34px;
}
#lineEdit {
  qproperty-clearButtonAllowed: false;
}
#lineEdit[qApp_deviceIsTrilogy=true] {
  max-width: 95px;
  min-width: 95px;
}
#lineEdit[qApp_deviceIsPhoenix=true] {
  max-width: 115px;
  min-width: 115px;
}
#lineEdit[qApp_deviceIsDragon=true] {
  max-width: 145px;
  min-width: 145px;
}
#lineEdit[qApp_deviceIsDaylight=true] {
  max-width: 185px;
  min-width: 185px;
}
#lineEdit[qApp_deviceIsStorm=true] {
  max-width: 170px;
  min-width: 170px;
}
#totalPages {
  padding-right: 0px;
}
#totalPages[localeName=\"ja\"] {
  qproperty-leading: 5;
  qproperty-textFormat: RichText;
}
#totalPages[localeName=\"zh\"] {
  qproperty-leading: 5;
  qproperty-textFormat: RichText;
}
#totalPages[localeName=\"zh-HK\"] {
  qproperty-leading: 5;
  qproperty-textFormat: RichText;
}
#totalPages[localeName=\"zh-TW\"] {
  qproperty-leading: 5;
  qproperty-textFormat: RichText;
}
```

</details>
